### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by TushtiSavarn**

### CODE REVIEW

**Review by Durgesh4993 — CHANGES_REQUESTED** [review]
image

**Comment by Durgesh4993** [comment]
@TushtiSavarn  Kindly check issue

**Comment by TushtiSavarn** [comment]
@Durgesh4993  Kindly check if my pull request is valid and visible . My apologies for mistakes and errors eariler one .Kindly tell if this one is right or not.

**Comment by Durgesh4993** [comment]
Don't forget to [Star](https://github.com/Girlscript-WOB/Open-source-Practice) repo & follow me on [GitHub](https://github.com/Durgesh4993) :)

**Review by Durgesh4993 — APPROVED** [review]
Approve

**Pull request merged**
